import Head from 'next/head'
import { useState } from 'react';

export default function Home() {

  const [error, setError] = useState();
  const [user, setuser] = useState({
    name: "",
    partner_name: "",
    left: "",
    right: ""
  })

  const areFieldsEmpty = () => {
    return user.name.trim() === "" || user.partner_name.trim() === "" || user.left.trim() === "" || user.right.trim() === "";
  };

  const getRandomNumber = (min = 0, max = 100) => {
    const result = Math.floor(Math.random() * (max - min + 1)) + min;
    setData(result)
  };
  const [data, setData] = useState();

  const handleChange = (e) => {
    const name = e.target.name;
    const value = e.target.value;
    setuser({ ...user, [name]: value });

  };

  const handleClick = () => {
    if (areFieldsEmpty()) {
      setError("Error: Name or partner_name is empty");
    } else {
      getRandomNumber();
      setError('');

    }
  };

  return (
    <>
      <Head>
        <title>LoveCalculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="outer">
        <h6 className='center'>designed by Pabitra Khadka</h6>
          <h2 className='center-text center'>Love Calculator By Name</h2>
          <div className="image">
            <img src="https://img.freepik.com/premium-photo/cute-boy-love-his-girl-friend-proposewith-heart_847288-498.jpg" alt="" />
          </div>

          <div className="center_div">


            <div class="login-box">

              <form>
                <div className="inputs d-flex">
                  <div className="input m-1">
                    <div class="user-box">
                      <input type="text" name="name" autoComplete='off' onChange={handleChange} value={user.name} required />
                      <label>Your Name</label>
                    </div>
                  </div>
                  <div className="input  m-1">
                    <div class="user-box">
                      <input type="text" name="partner_name" autoComplete='off'  onChange={handleChange} value={user.partner_name} required />
                      <label>Your Partner's Name</label>
                    </div>
                  </div>
                </div>
                <div className="flex_select d-flex">
                  <div className="select_gender m-1">

                    <select class="form-select form-select-sm" aria-label=".form-select-sm example" onChange={handleChange} name='left' value={user.left}>
                      <option selected>Select Gender</option>
                      <option value="male">Male</option>
                      <option value="female">Female</option>

                    </select>
                  </div>
                  <div className="select_gender m-1">

                    <select class="form-select form-select-sm" aria-label=".form-select-sm example" onChange={handleChange} name='right' value={user.right}>
                      <option selected>Select Gender</option>
                      <option value="male">Male</option>
                      <option value="female">Female</option>
                    </select>
                  </div>
                </div>

                <center>

                  <button type='submit' onClick={handleClick}>
                    <a href="#">
                      Calculate
                      <span></span>
                    </a>
                  </button>
                  <h1 className='mt-3 result'>{data}%</h1>
                  <p className='error_line'>{error}</p>
                </center>
              </form>
            </div>

          </div>

        </div>
      </main>
    </>
  )
}
